# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode: true

# Custom rules for dartfmt
dart_style:
  # Set the number of spaces for indentation
  line-length: 120
  indent: 2

  # Control whether to format collections (lists, maps, sets) with a single item per line.
  # true: Single item per line
  # false: All items in a single line
  collection_literals: true

  # Control whether to format named arguments in a function call with a single argument per line.
  # true: Single argument per line
  # false: All arguments in a single line
  single_cascade_in_expression_statements: true

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    avoid_print: false
    prefer_const_constructors: false
    use_full_hex_values_for_flutter_colors: false
    prefer_const_literals_to_create_immutables: false
    library_private_types_in_public_api: false
    no_leading_underscores_for_local_identifiers: false
    deprecated_member_use_from_same_package: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
