// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATrCGV-iGFrrwDSiIkgFKjonJW_UQj33s',
    appId: '1:287475777177:web:28486cb2b6f7b70807c208',
    messagingSenderId: '287475777177',
    projectId: 'vuboi-fitness',
    authDomain: 'vuboi-fitness.firebaseapp.com',
    storageBucket: 'vuboi-fitness.appspot.com',
    measurementId: 'G-SEN5P5TQLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfCL31EZVoXFQYXUFx_cQGjgLAf24wPdE',
    appId: '1:287475777177:android:8a1cf0e128f2b4b807c208',
    messagingSenderId: '287475777177',
    projectId: 'vuboi-fitness',
    storageBucket: 'vuboi-fitness.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABD8rLNVIyn631vwkR8QrJgIO1b4_iZR4',
    appId: '1:287475777177:ios:b9993067252f4ecd07c208',
    messagingSenderId: '287475777177',
    projectId: 'vuboi-fitness',
    storageBucket: 'vuboi-fitness.appspot.com',
    iosClientId: '287475777177-1hv5m7nucdo8gklkmuhsmsgj9636682u.apps.googleusercontent.com',
    iosBundleId: 'com.vuboi.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABD8rLNVIyn631vwkR8QrJgIO1b4_iZR4',
    appId: '1:287475777177:ios:9d7d953749e8afb207c208',
    messagingSenderId: '287475777177',
    projectId: 'vuboi-fitness',
    storageBucket: 'vuboi-fitness.appspot.com',
    iosClientId: '287475777177-1a442jli5vukhrif1v3jlp6tnhlqfs8h.apps.googleusercontent.com',
    iosBundleId: 'com.vuboi.fitness.RunnerTests',
  );
}
